version: '3.4'

services:

  computers.angular.app:
    image: ${DOCKER_REGISTRY-}angularapp
    build:
      context: .
      dockerfile: ComputersApp.Api/ClientApp/Dockerfile
    ports:
      - "4200:4200" 
    volumes:
      - ./ComputersApp.Api/ClientApp:/app

  computersapp:
    image: ${DOCKER_REGISTRY-}aspnetcoreapp
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"  
    build:
      context: .
      dockerfile: ComputersApp.Api/Dockerfile
      args:
        - skip_client_build=false
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro  